/*
This procedure calculates the total power generated by each panel array in a given system 
by considering the specifications of the panels and their usage.
 */
-- Procedure: CalculateTotalPowerGenerated
DELIMITER / / CREATE PROCEDURE CalculateTotalPowerGenerated (IN pvSystemId INT) BEGIN DECLARE totalPower DECIMAL(10, 2);

-- Temporary table to store intermediate results
CREATE TEMPORARY TABLE TempPanelPower (panelArrayId INT, totalPanelPower DECIMAL(10, 2));

-- Calculate power for each panel array
INSERT INTO
    TempPanelPower (panelArrayId, totalPanelPower)
SELECT
    pa.id,
    (spp.max_power_current * pu.quantity) AS panelArrayPower
FROM
    panel_arrays pa
    JOIN panel_usage pu ON pa.id = pu.panel_array_id
    JOIN specifications_panel_products spp ON pu.panel_product_id = spp.id
WHERE
    pa.pv_system_id = pvSystemId;

-- Calculate total power for the system
SELECT
    SUM(totalPanelPower) INTO totalPower
FROM
    TempPanelPower;

-- Display or use the total power
SELECT
    totalPower AS 'Total Power Generated for System';

-- Drop the temporary table
DROP TEMPORARY TABLE IF EXISTS TempPanelPower;

END / / DELIMITER;