/*
CalculateSystemEfficiency is designed to calculate and display the efficiency of a 
solar power system identified by a given pvSystemId. The efficiency is determined by comparing the 
total power consumed by the system  (including inverter and battery power) to the total power generated by the solar panels.
 */
-- Procedure: CalculateSystemEfficiency
DELIMITER / / CREATE PROCEDURE CalculateSystemEfficiency (IN pvSystemId INT) BEGIN DECLARE totalPowerGenerated DECIMAL(10, 2);

DECLARE totalPowerConsumed DECIMAL(10, 2);

DECLARE systemEfficiency DECIMAL(4, 2);

-- Temporary table to store intermediate results
CREATE TEMPORARY TABLE TempPower (
    totalPowerGenerated DECIMAL(10, 2),
    totalPowerConsumed DECIMAL(10, 2)
);

-- Calculate total power generated and consumed
INSERT INTO
    TempPower (totalPowerGenerated, totalPowerConsumed)
SELECT
    SUM(irradiance * inverter_efficiency) AS generated,
    SUM(
        COALESCE(inverter_ac_power, 0) + COALESCE(battery_dc_power, 0)
    ) AS consumed
FROM
    log_status_pv_system_minutes
WHERE
    pv_system_id = pvSystemId;

-- Fetch total power values
SELECT
    totalPowerGenerated,
    totalPowerConsumed INTO totalPowerGenerated,
    totalPowerConsumed
FROM
    TempPower;

-- Calculate system efficiency
IF totalPowerGenerated > 0 THEN
SET
    systemEfficiency = (totalPowerConsumed / totalPowerGenerated) * 100;

ELSE
SET
    systemEfficiency = 0;

END IF;

-- Display or use the system efficiency
SELECT
    CONCAT (
        'System Efficiency for System: ',
        systemEfficiency
    ) AS result;

-- Drop the temporary table
DROP TEMPORARY TABLE IF EXISTS TempPower;

END / / DELIMITER;